spring.application.name=hrms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.datasource.url=jdbc:h2:mem:hrms;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=very-secret-key-for-hrms-project-123456
jwt.expiration=86400000